In [87]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [88]:
df = pd.read_csv("loan_approval_data.csv")

In [89]:
df.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes

In [90]:
df.isnull().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [91]:
df.shape

(1000, 20)

In [92]:
df = df.drop("Applicant_ID", axis = 1)

In [93]:
columns_to_hot_enocde = ["Employment_Status", "Marital_Status", "Loan_Purpose", "Property_Area", "Education_Level", "Gender", "Employer_Category"]

In [94]:
df = pd.get_dummies(df, columns=columns_to_hot_enocde)

In [95]:
df

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Property_Area_Urban,Education_Level_Graduate,Education_Level_Not Graduate,Gender_Female,Gender_Male,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed
0,17795.0,1387.0,51.0,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,...,True,False,True,True,False,False,False,False,True,False
1,2860.0,2679.0,46.0,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,...,False,True,False,False,False,False,False,False,True,False
2,7390.0,2106.0,25.0,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,...,True,False,False,True,False,False,True,False,False,False
3,13964.0,8173.0,40.0,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,...,False,True,False,True,False,False,True,False,False,False
4,13284.0,4223.0,31.0,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,...,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,9092.0,58.0,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,...,False,False,True,False,True,False,False,False,False,True
996,3279.0,6356.0,58.0,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,...,True,True,False,True,False,False,True,False,False,False
997,15192.0,8433.0,48.0,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,...,False,True,False,False,True,False,False,True,False,False
998,9083.0,7380.0,50.0,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,...,True,True,False,False,True,False,False,False,True,False
999,13093.0,2385.0,23.0,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,...,False,True,False,False,False,False,False,False,True,False

In [96]:
df.columns

Index(['Applicant_Income', 'Coapplicant_Income', 'Age', 'Dependents',
       'Credit_Score', 'Existing_Loans', 'DTI_Ratio', 'Savings',
       'Collateral_Value', 'Loan_Amount', 'Loan_Term', 'Loan_Approved',
       'Employment_Status_Contract', 'Employment_Status_Salaried',
       'Employment_Status_Self-employed', 'Employment_Status_Unemployed',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Loan_Purpose_Business', 'Loan_Purpose_Car', 'Loan_Purpose_Education',
       'Loan_Purpose_Home', 'Loan_Purpose_Personal', 'Property_Area_Rural',
       'Property_Area_Semiurban', 'Property_Area_Urban',
       'Education_Level_Graduate', 'Education_Level_Not Graduate',
       'Gender_Female', 'Gender_Male', 'Employer_Category_Business',
       'Employer_Category_Government', 'Employer_Category_MNC',
       'Employer_Category_Private', 'Employer_Category_Unemployed'],
      dtype='object')

In [97]:
df = df.dropna(subset=["Loan_Approved"]).copy()
df.fillna(df.median(numeric_only=True), inplace=True)

In [98]:
Y = df["Loan_Approved"].map({"Yes": 1, "No": 0})
Y.isnull().sum()

np.int64(0)

In [99]:
df

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Property_Area_Urban,Education_Level_Graduate,Education_Level_Not Graduate,Gender_Female,Gender_Male,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed
0,17795.0,1387.0,51.0,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,...,True,False,True,True,False,False,False,False,True,False
1,2860.0,2679.0,46.0,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,...,False,True,False,False,False,False,False,False,True,False
2,7390.0,2106.0,25.0,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,...,True,False,False,True,False,False,True,False,False,False
3,13964.0,8173.0,40.0,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,...,False,True,False,True,False,False,True,False,False,False
4,13284.0,4223.0,31.0,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,...,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10452.5,9092.0,58.0,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,...,False,False,True,False,True,False,False,False,False,True
996,3279.0,6356.0,58.0,1.0,646.0,3.0,0.19,9910.0,18361.0,22563.0,...,True,True,False,True,False,False,True,False,False,False
997,15192.0,8433.0,48.0,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,...,False,True,False,False,True,False,False,True,False,False
998,9083.0,7380.0,50.0,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,...,True,True,False,False,True,False,False,False,True,False
999,13093.0,2385.0,23.0,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,...,False,True,False,False,False,False,False,False,True,False

In [100]:
X = df.drop("Loan_Approved", axis=1)

In [101]:
X

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Property_Area_Urban,Education_Level_Graduate,Education_Level_Not Graduate,Gender_Female,Gender_Male,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed
0,17795.0,1387.0,51.0,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,...,True,False,True,True,False,False,False,False,True,False
1,2860.0,2679.0,46.0,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,...,False,True,False,False,False,False,False,False,True,False
2,7390.0,2106.0,25.0,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,...,True,False,False,True,False,False,True,False,False,False
3,13964.0,8173.0,40.0,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,...,False,True,False,True,False,False,True,False,False,False
4,13284.0,4223.0,31.0,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,...,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10452.5,9092.0,58.0,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,...,False,False,True,False,True,False,False,False,False,True
996,3279.0,6356.0,58.0,1.0,646.0,3.0,0.19,9910.0,18361.0,22563.0,...,True,True,False,True,False,False,True,False,False,False
997,15192.0,8433.0,48.0,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,...,False,True,False,False,True,False,False,True,False,False
998,9083.0,7380.0,50.0,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,...,True,True,False,False,True,False,False,False,True,False
999,13093.0,2385.0,23.0,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,...,False,True,False,False,False,False,False,False,True,False

In [102]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [103]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train.values)
X_test = scaler.transform(X_test.values)

In [104]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [107]:
y_prob = model.predict_proba(X_test)[:, 1]
y_pred = (y_prob > 0.4).astype(int)

In [108]:
from sklearn.metrics import accuracy_score, r2_score, recall_score, confusion_matrix, classification_report
acc = accuracy_score(Y_test, y_pred)
recall = recall_score(Y_test, y_pred)
cm = confusion_matrix(Y_test, y_pred)
report = classification_report(Y_test, y_pred)

print("Accuracy:", acc)
print("Recall:", recall)
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

Accuracy: 0.9052631578947369
Recall: 0.819672131147541

Confusion Matrix:
 [[122   7]
 [ 11  50]]

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.95      0.93       129
           1       0.88      0.82      0.85        61

    accuracy                           0.91       190
   macro avg       0.90      0.88      0.89       190
weighted avg       0.90      0.91      0.90       190

In [109]:
from sklearn.metrics import roc_auc_score
print(roc_auc_score(Y_test, y_prob))

0.951709238785106